# Generated by Django 2.0.13 on 2019-06-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articel',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
